spring:
  datasource:
    url: jdbc:mysql://localhost:3306/work4?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 222316
  data:
    redis:
      host: 192.168.190.131
      port: 6379
      password: 222316
      database: 0
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    mybatis-plus: DEBUG
  

my:
 secret: ygh112233