spring:
 datasource:
  url: jdbc:mysql://localhost:3306/work4?useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: 222316
mybatis-plus:
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
   mybatis-plus: DEBUG