spring:
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

---

spring:
  config:
    activate: 
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/work4?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 222316
  data:
    redis:
      host: 192.168.190.131
      port: 6379
      password: 222316
      database: 0
my:
 secret: ygh112233
 avatar_address: D:\code\javalearning\work4\avatars\
 video_address: D:\code\javalearning\work4\videos\
logging:
  level:
    mybatis-plus: DEBUG

---

spring:
  config:
    activate:
      on-profile: pro
  datasource:
    url: jdbc:mysql://localhost:3306/work4?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 222316
  data:
    redis:
      host: localhost
      port: 6379
      password: 222316
      database: 1
my:
 secret: ygh112233
 avatar_address: /root/work4/avatars/
 video_address: /root/work4/videos/
logging:
  level:
    mybatis-plus: INFO


  

